### ISSUE TITLE
python3 main.py --rfc 8825 でエラー

### ISSUE THREAD

**Issue by kekemoto** [tex2e/rfc-translater#1]
タイトル通りです。  
以下はエラーログです。

```shell
% python3 main.py --rfc 8825
RFC 8825:
RFC 8825:   0%|                                                                                                                                                                  | 0/182 [00:00<?]Traceback (most recent call last):
  File "/Users/kekemoto/code/rfc-translater/main.py", line 86, in <module>
    main(rfc)
  File "/Users/kekemoto/code/rfc-translater/main.py", line 28, in main
    res = trans_rfc(rfc_number)
  File "/Users/kekemoto/code/rfc-translater/src/trans_rfc.py", line 113, in trans_rfc
    ja = translator.translate(text)
  File "/Users/kekemoto/code/rfc-translater/src/trans_rfc.py", line 53, in translate
    ja = self.translator.translate(text, dest='ja')
  File "/usr/local/lib/python3.9/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/usr/local/lib/python3.9/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.9/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/usr/local/lib/python3.9/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
RFC 8825:   0%|               
```

### 試したこと
新規のRFCではなく、既に作成されているものを対象にしても同じエラーでした。  
`python3 main.py --rfc 8800`

### 環境
```shell
% python3 --version
Python 3.9.1

% pip3 --version   
pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

% pip3 list        
Package        Version
-------------- ----------
beautifulsoup4 4.9.3
certifi        2020.12.5
chardet        3.0.4
googletrans    3.0.0
h11            0.9.0
h2             3.2.0
hpack          3.0.0
hstspreload    2020.12.22
httpcore       0.9.1
httpx          0.13.3
hyperframe     5.2.0
idna           2.10
lxml           4.6.2
Mako           1.1.4
MarkupSafe     1.1.1
pip            21.0.1
requests       2.25.1
rfc3986        1.4.0
setuptools     52.0.0
sniffio        1.2.0
soupsieve      2.2
tqdm           4.56.2
urllib3        1.26.3
wheel          0.36.2
```
OS：macOS 11.2

### 推測
単純にライブラリのバージョンが一致してないだけなんじゃないかと思っています。  
成功している環境のバージョンが知りたいです。

### その他
めちゃくちゃ便利に使わさせて貰ってます！ありがとうございます！  
Python 全然分からないので、修正などはできず申し訳ないです。

**Comment by tex2e** [comment]
googletransは非公式の翻訳ライブラリでGoogle翻訳のAPIの仕組みが変わると使えなくなってしまいます。
2020年10月くらいから 3.0.0 は使えなくなっていて、4.0.0-rc1 にすると動いたり動かなかったりします（自分の環境では、最初の数回は動くけど、何回か翻訳するとエラーになる感じでした）。

googletransの対応次第ですが、さらに数か月待っても変化がなければ、seleniumを使って翻訳するなどの別手段も用意しておこうと思います。

詳細：[error in result (AttributeError: 'NoneType' object has no attribute 'group') · Issue #234 · ssut/py-googletrans](https://github.com/ssut/py-googletrans/issues/234)

追記：
回避策として、ChromeでRFCのHTML版 https://www.rfc-editor.org/rfc/rfc8825.html にアクセスし、画面右クリックから「日本語に翻訳」をするようお願いいたします。

**Comment by tex2e** [comment]
- デフォルトの翻訳方法をseleniumからGoogle翻訳に変更しました。
- RFC 8825までを翻訳して公開しました。https://tex2e.github.io/rfc-translater/html/rfc8825.html

**Comment by kekemoto** [comment]
ありがとうございます！
